server:
  host: 0.0.0.0
  port: 3000
  cors:
    - "http://0.0.0.0:4200"
    - "http://127.0.0.1:4200"
    - "http://localhost:4200"
swagger:
  title: MusicOrganizer API
  description: A NestJS Music API for all
  version: 1.0
  musicTag: music
  userTag: user
  playlistTag: playlist
  path: documentation
mongodb:
  uri: mongodb://0.0.0.0:27017/MusicOrganizer
  options:
    useNewUrlParser: true
    useUnifiedTopology: true
    useFindAndModify: false
