server:
  host: 0.0.0.0
  port: 3000
swagger:
  title: MusicOrganizer API NestJS
  description: A NestJS Music API for all
  version: 1.0
  tag: music
  path: documentation
mongodb:
  uri: mongodb://0.0.0.0:27017/MusicOrganizer
  options:
    useNewUrlParser: true
    useUnifiedTopology: true
    useFindAndModify: false
